project:
  type: website

website:
  title: "Into to Occupancy Modelling"
  navbar:
    left:
      - text: "Intro to Occupancy"
        href: Occupancy_Models.qmd
      - text: "Covariates"
        href: OccMods_WithCovariates.qmd
      - text: "Bayesian & Spatial"
        href: Bayesian_Occupancy_Models.qmd

format:
  html:
    theme: cosmo
    toc: true